[package]
name = "oxplay-media"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[features]
native-rendering = ["dep:wgpu", "dep:ash", "dep:windows"]

[dependencies]
slint.workspace = true
glow = "0.18"
wgpu = { version = "=30.0.1", default-features = false, features = ["std", "wgsl", "metal", "vulkan", "dx12"], optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_System_Power"] }
windows = { version = "=0.62.2", optional = true, features = ["Win32_Foundation", "Win32_Security", "Win32_Graphics_Direct3D", "Win32_Graphics_Direct3D11", "Win32_Graphics_Direct3D12", "Win32_Graphics_Dxgi", "Win32_Graphics_Dxgi_Common", "Win32_System_Com", "Win32_System_Threading"] }

[target.'cfg(target_os = "linux")'.dependencies]
ash = { version = "=0.38.0", optional = true }

[build-dependencies]
pkg-config = "0.3"
cc = "=1.5.1"
