[package]
name = "serein-youtube"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
serein-core = { path = "../core" }
serde_json = "1"
url = "2.5"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "stream"] }
tokio = { version = "1", features = ["rt", "time", "net", "sync", "macros"] }
sha1 = "0.10"
zeroize = "1"
httpdate = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
