#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Build and inspect unsigned native Linux packages (deb, rpm, Arch) for Oxplay.

Installs nothing and never launches Oxplay. Standard library plus the native
distribution packaging tools; each format is built on its own distribution so
shared-library dependencies match what the binary was linked against.

Layout (all formats):
  /usr/bin/oxplay                   launcher selecting the packaged helpers
  /usr/lib/oxplay/oxplay            application ELF
  /usr/lib/oxplay/{yt-dlp,deno}     pinned, SHA-256-verified helpers
  /usr/lib/oxplay/libmpv.so.2       only with --mpv-prefix (private libmpv; RUNPATH $ORIGIN)
"""
from __future__ import annotations

import argparse
import filecmp
import os
from pathlib import Path
import platform
import re
import shutil
import struct
import subprocess
import sys
import tarfile
import tempfile
import tomllib

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "packaging"))
import notices  # noqa: E402

APP_ID = "cz.viceverse.oxplay"
SEMVER = re.compile(r"[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?")
LAUNCHER = """#!/bin/sh
# Oxplay launcher (generated by packaging/linux/package.py). Adds the packaged
# yt-dlp and Deno unless the caller selected helpers or a diagnostic mode.
set -eu
root={root}
yt_dlp=1
deno=1
for argument in "$@"; do
  case $argument in
    --yt-dlp) yt_dlp=0 ;;
    --deno) deno=0 ;;
    --help|--*-smoke-test|--*-check) yt_dlp=0; deno=0 ;;
  esac
done
if [ "$deno" = 1 ]; then set -- --deno "$root/lib/oxplay/deno" "$@"; fi
if [ "$yt_dlp" = 1 ]; then set -- --yt-dlp "$root/lib/oxplay/yt-dlp" "$@"; fi
exec "$root/{executable}" "$@"
"""
SYSTEM_ROOT = "/usr"
# AppImage/tarball: usr/ is two levels above the resolved launcher.
PORTABLE_ROOT = '"$(dirname -- "$(dirname -- "$(readlink -f -- "$0")")")"'


def output(*args: str | Path, cwd: Path | None = None, env: dict | None = None) -> str:
    return subprocess.check_output([str(arg) for arg in args], cwd=cwd, text=True, env=env).strip()


def checked(*args: str | Path, cwd: Path | None = None) -> None:
    subprocess.run([str(arg) for arg in args], cwd=cwd, check=True)


def workspace_version() -> str:
    return tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))["workspace"]["package"]["version"]


def elf_machine(path: Path) -> int:
    with path.open("rb") as stream:
        header = stream.read(20)
    if len(header) != 20 or header[:6] != b"\x7fELF\x02\x01":
        raise ValueError(f"Expected a little-endian 64-bit ELF file: {path.name}")
    return struct.unpack("<H", header[18:20])[0]


def native_elf(path: Path) -> None:
    """Refuse to label a cross-built binary with the host architecture."""
    expected = {"x86_64": 62, "aarch64": 183}.get(platform.machine())
    if sys.platform != "linux" or expected is None or elf_machine(path) != expected:
        raise ValueError(f"Expected a native Linux ELF file for this host: {path.name}")


def is_elf(path: Path) -> bool:
    with path.open("rb") as stream:
        return stream.read(4) == b"\x7fELF"


def launcher(root: str, executable: str) -> str:
    return LAUNCHER.format(root=root, executable=executable)


def mpv_library(prefix: Path) -> Path:
    library = (prefix / "lib/libmpv.so.2").resolve(strict=True)
    native_elf(library)
    return library


def mpv_description(prefix: Path | None, portable: bool = False) -> str:
    if prefix is None:
        return "the distribution's libmpv package (not bundled)"
    source = (prefix / "ci-source.txt").read_text(encoding="utf-8").strip()
    where = ("bundled in usr/lib with its non-system shared-library closure (FFmpeg and others, "
             "copied from Ubuntu 24.04 packages)" if portable else "bundled as /usr/lib/oxplay/libmpv.so.2, "
             "linking the distribution's FFmpeg and libraries")
    return (f"private build of {source}; {where}. Unmodified upstream source "
            "https://github.com/mpv-player/mpv (GPL-2.0-or-later)")


def executables(prefix: str) -> set[str]:
    return {f"{prefix}/bin/oxplay", f"{prefix}/lib/oxplay/oxplay", f"{prefix}/lib/oxplay/yt-dlp",
            f"{prefix}/lib/oxplay/deno"}


def normalize_modes(stage: Path, executable: set[str]) -> None:
    for path in [stage, *stage.rglob("*")]:
        relative = path.relative_to(stage).as_posix()
        path.chmod(0o755 if path.is_dir() or relative in executable else 0o644)


def copy_file(source: Path, destination: Path) -> None:
    if source.is_symlink() and not source.resolve(strict=True).is_file():
        raise ValueError(f"Refusing a non-file package input: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source.resolve(strict=True), destination)


def stage_payload(stage: Path, binary: Path, helpers: Path, mpv_prefix: Path | None, portable: bool = False) -> None:
    """Allowlisted installation payload shared by every native format.

    `portable` (AppImage/tarball) makes the launcher locate usr/ relative to
    itself and leaves native library bundling to packaging/appimage/build.py.
    """
    usr = stage / "usr"
    lib = usr / "lib/oxplay"
    copy_file(binary, lib / "oxplay")
    for name in ("yt-dlp", "deno"):
        copy_file(helpers / name, lib / name)
        if not is_elf(lib / name):
            raise ValueError(f"The pinned {name} helper is not a Linux executable")
    (usr / "bin").mkdir(parents=True)
    (usr / "bin/oxplay").write_text(launcher(PORTABLE_ROOT if portable else SYSTEM_ROOT, "lib/oxplay/oxplay"),
                                    encoding="utf-8")
    doc = usr / "share/doc/oxplay"
    if mpv_prefix is not None:
        if not portable:
            copy_file(mpv_library(mpv_prefix), lib / "libmpv.so.2")
            # Resolve the private libmpv beside the executable without LD_LIBRARY_PATH,
            # which would leak into helpers and browsers started by the app.
            checked("patchelf", "--set-rpath", "$ORIGIN", lib / "oxplay")
        copy_file(mpv_prefix / "ci-source.txt", doc / "MPV-SOURCE.txt")
        copy_file(mpv_prefix / "ci-build-options.json", doc / "mpv-build-options.json")
    copy_file(ROOT / "packaging/linux" / f"{APP_ID}.desktop", usr / "share/applications" / f"{APP_ID}.desktop")
    copy_file(ROOT / "packaging/linux/oxplay.svg", usr / "share/icons/hicolor/scalable/apps/oxplay.svg")
    copy_file(ROOT / "LICENSE", doc / "LICENSE")
    copy_file(ROOT / "README.md", doc / "README.md")
    notices.copy_helper_licenses(doc / "licenses")
    (doc / "THIRD-PARTY-NOTICES.md").write_text(
        notices.render(notices.pinned_inputs(helpers), mpv_description(mpv_prefix, portable)), encoding="utf-8")
    normalize_modes(stage, executables("usr"))


def payload_files(root: Path) -> list[str]:
    return sorted(path.relative_to(root).as_posix() for path in root.rglob("*") if path.is_file())


def check_payload(stage: Path, extracted: Path, ignore: tuple[str, ...] = ()) -> None:
    expected = [name for name in payload_files(stage) if not name.startswith(ignore)]
    if payload_files(extracted) != expected:
        raise ValueError("Package payload differs from the staged allowlist")
    for name in expected:
        path = extracted / name
        if path.is_symlink() or not filecmp.cmp(stage / name, path, shallow=False):
            raise ValueError(f"Package changed file contents: {name}")


def closure_check(stage: Path) -> str:
    libraries = output("ldd", stage / "usr/lib/oxplay/oxplay")
    if "not found" in libraries:
        raise ValueError(f"Unresolved packaged executable dependencies:\n{libraries}")
    return libraries


def elf_payload(stage: Path) -> list[Path]:
    return sorted(path for path in (stage / "usr/lib/oxplay").iterdir() if path.is_file() and is_elf(path))


# --- Debian ---------------------------------------------------------------------

def deb_version(version: str) -> str:
    return version.replace("-", "~", 1) + "-1"


def deb_package(workdir: Path, stage: Path, version: str, private_mpv: bool) -> Path:
    architecture = output("dpkg", "--print-architecture")
    if architecture not in {"amd64", "arm64"}:
        raise ValueError(f"Unverified Debian package architecture: {architecture}")
    package_version = deb_version(version)
    checked("dpkg", "--validate-version", package_version)
    (workdir / "debian/control").write_text(
        "Source: oxplay\nSection: video\nPriority: optional\n"
        "Maintainer: Oxplay contributors <noreply@github.com>\n\n"
        "Package: oxplay\nArchitecture: any\nDescription: Experimental native YouTube client\n", encoding="utf-8")
    (stage / "DEBIAN").mkdir()
    relative = [path.relative_to(workdir).as_posix() for path in elf_payload(stage)]
    # The private libmpv lives in this package; dpkg-shlibdeps resolves it here.
    dependencies = output("dpkg-shlibdeps", "-O", "--ignore-missing-info",
                          f"-l{(stage / 'usr/lib/oxplay').relative_to(workdir).as_posix()}", *relative, cwd=workdir)
    depends = next(line.removeprefix("shlibs:Depends=") for line in dependencies.splitlines()
                   if line.startswith("shlibs:Depends="))
    if not private_mpv and "libmpv" not in depends:
        raise ValueError("The system libmpv dependency was not detected")
    # dlopen()ed by winit/Slint and not visible as ELF DT_NEEDED.
    depends += ", libegl1, libgl1, libxkbcommon0, libxkbcommon-x11-0, libwayland-client0, libwayland-egl1, " \
               "libx11-6, libxcursor1, libxi6, libxrandr2, libfontconfig1"
    installed_kib = sum(1 if path.is_dir() else max(1, (path.stat().st_size + 1023) // 1024)
                        for path in stage.rglob("*") if not path.relative_to(stage).as_posix().startswith("DEBIAN"))
    (stage / "DEBIAN/control").write_text(
        f"Package: oxplay\nVersion: {package_version}\nArchitecture: {architecture}\n"
        "Section: video\nPriority: optional\nMaintainer: Oxplay contributors <noreply@github.com>\n"
        "Homepage: https://github.com/ViceVerse-cz/oxplay\n"
        f"Installed-Size: {installed_kib}\nDepends: {depends}\n"
        "Recommends: xdg-desktop-portal, xdg-utils\n"
        "Description: Experimental native YouTube client\n"
        " Native Rust/Slint YouTube client with in-process libmpv playback.\n"
        " Bundles pinned yt-dlp and Deno helpers. Experimental and unofficial.\n", encoding="utf-8")
    normalize_modes(stage, executables("usr"))
    artifact = workdir / f"oxplay_{package_version}_{architecture}.deb"
    checked("dpkg-deb", "--root-owner-group", "-Zxz", "--build", stage, artifact)
    for field, expected in {"Package": "oxplay", "Version": package_version, "Architecture": architecture,
                            "Depends": depends}.items():
        actual = output("dpkg-deb", "--field", artifact, field)
        if actual != expected:
            raise ValueError(f"Package {field}: expected {expected!r}, got {actual!r}")
    # Inspect members before extraction: no links, devices, traversal or odd owners/modes.
    archive = workdir / "payload.tar"
    with archive.open("wb") as stream:
        subprocess.run(["dpkg-deb", "--fsys-tarfile", str(artifact)], stdout=stream, check=True)
    runnable = {"./" + name for name in executables("usr")}
    with tarfile.open(archive) as contents:
        for member in contents:
            path = Path(member.name)
            mode = 0o755 if member.isdir() or member.name in runnable else 0o644
            if (path.is_absolute() or ".." in path.parts or not (member.isfile() or member.isdir())
                    or member.mode != mode or member.uid or member.gid):
                raise ValueError(f"Unsafe package entry or incorrect mode/owner: {member.name}")
    extracted = workdir / "extracted"
    checked("dpkg-deb", "--extract", artifact, extracted)
    check_payload(stage, extracted, ignore=("DEBIAN/",))
    control = workdir / "extracted-control"
    checked("dpkg-deb", "--control", artifact, control)
    if payload_files(control) != ["control"]:
        raise ValueError("Unexpected control files or maintainer scripts")
    checked("desktop-file-validate", extracted / "usr/share/applications" / f"{APP_ID}.desktop")
    closure_check(extracted)
    print(f"Debian package smoke passed: {len(payload_files(extracted))} files; Depends: {depends}")
    return artifact


# --- RPM ------------------------------------------------------------------------------

def rpm_version(version: str) -> str:
    return version.replace("-", "~", 1).replace("-", ".")


def rpm_package(workdir: Path, stage: Path, version: str, distro: str) -> Path:
    package_version = rpm_version(version)
    release = "1.fc" + platform.freedesktop_os_release()["VERSION_ID"] if distro == "fedora" else "1.suse"
    if not re.fullmatch(r"1\.(?:fc[0-9]+|suse)", release):
        raise ValueError("Unsupported RPM distribution version")
    # rpmbuild adds the ELF SONAME requirements (including libmpv.so.2) itself.
    requires = [f"{soname}()(64bit)" for soname in (
        "libEGL.so.1", "libxkbcommon.so.0", "libwayland-client.so.0", "libX11.so.6", "libXcursor.so.1",
        "libXi.so.6", "libXrandr.so.2", "libfontconfig.so.1")]
    files = [f"/{name}" for name in payload_files(stage)]
    spec = workdir / "oxplay.spec"
    spec.write_text(
        # Never strip or split: PyInstaller's yt-dlp stores its archive past the ELF image.
        "%global debug_package %{nil}\n%global __os_install_post %{nil}\n%global _build_id_links none\n"
        f"Name: oxplay\nVersion: {package_version}\nRelease: {release}\n"
        "Summary: Experimental native YouTube client\nLicense: GPL-3.0-or-later\n"
        "URL: https://github.com/ViceVerse-cz/oxplay\n"
        + "".join(f"Requires: {item}\n" for item in requires)
        + "Recommends: xdg-desktop-portal, xdg-utils\n"
        "\n%description\nNative Rust/Slint YouTube client with in-process libmpv playback.\n"
        "Bundles pinned yt-dlp and Deno helpers. Experimental and unofficial.\n"
        "\n%install\nmkdir -p %{buildroot}\ncp -a %{_oxplay_payload}/. %{buildroot}/\n"
        "\n%files\n%defattr(-,root,root,-)\n%dir /usr/lib/oxplay\n%dir /usr/share/doc/oxplay\n"
        "%dir /usr/share/doc/oxplay/licenses\n" + "\n".join(files) + "\n", encoding="utf-8")
    # Paths become RPM macro values; reject macro and shell metacharacters.
    if not re.fullmatch(r"[/A-Za-z0-9_.-]+", str(workdir)):
        raise ValueError("RPM work directory must have a simple absolute path")
    checked("rpmbuild", "-bb", "--define", f"_topdir {workdir}/rpm", "--define", f"_oxplay_payload {stage}", spec)
    artifact, = (workdir / "rpm/RPMS").rglob("*.rpm")
    actual = output("rpm", "-qp", "--qf", "%{NAME}\n%{VERSION}\n%{RELEASE}\n%{ARCH}", artifact)
    if actual != f"oxplay\n{package_version}\n{release}\n{platform.machine()}":
        raise ValueError(f"Incorrect RPM metadata: {actual}")
    if output("rpm", "-qp", "--scripts", artifact):
        raise ValueError("Unexpected RPM install scripts")
    runnable = {"/" + name for name in executables("usr")}
    for line in output("rpm", "-qp", "--qf", "[%{FILENAMES}\t%{FILEMODES:octal}\t%{FILEUSERNAME}\t%{FILEGROUPNAME}\n]",
                       artifact).splitlines():
        name, mode, user, group = line.split("\t")
        path = stage / name.removeprefix("/")
        expected = 0o40755 if path.is_dir() else 0o100755 if name in runnable else 0o100644
        if ".." in Path(name).parts or not path.exists() or int(mode, 8) != expected or (user, group) != ("root", "root"):
            raise ValueError(f"Unexpected RPM payload entry: {line}")
    archive = workdir / "payload.cpio"
    with archive.open("wb") as stream:
        subprocess.run(["rpm2cpio", str(artifact)], stdout=stream, check=True)
    extracted = workdir / "extracted"
    extracted.mkdir()
    with archive.open("rb") as stream:
        subprocess.run(["cpio", "-id", "--no-absolute-filenames", "--quiet"], stdin=stream, cwd=extracted, check=True)
    check_payload(stage, extracted)
    actual_requires = output("rpm", "-qp", "--requires", artifact).splitlines()
    if not set(requires + ["libmpv.so.2()(64bit)"]).issubset(actual_requires):
        raise ValueError("Missing RPM runtime dependencies")
    print("RPM smoke passed: metadata, libmpv/SONAME requirements, payload contents, modes, owners and no scripts.")
    return artifact


# --- Arch -------------------------------------------------------------------------

def arch_version(version: str) -> str:
    # pacman sorts a letter suffix below the final release; '_' would sort above it.
    return version.replace("-", "pre.", 1).replace("-", ".")


def arch_package(workdir: Path, stage: Path, version: str) -> Path:
    package_version = arch_version(version)
    depends = {"libglvnd", "libxkbcommon", "libxkbcommon-x11", "wayland", "libx11", "libxcursor", "libxi",
               "libxrandr", "fontconfig"}
    for elf in elf_payload(stage):
        libraries = output("ldd", elf)
        for path in re.findall(r"(?:=>\s+|^\s*)(/\S+)", libraries, re.MULTILINE):
            owner = output("pacman", "-Qqo", path)
            name, installed = output("pacman", "-Q", owner).split()
            if name in {"zlib", "zlib-ng-compat"} or Path(path).name.startswith("libz.so"):
                depends.add("libz.so")  # satisfied by either zlib implementation
                continue
            depends.add(f"{name}>={installed}")
    if any(not re.fullmatch(r"[A-Za-z0-9@._+:>=-]+", item) for item in depends):
        raise ValueError("Invalid native Arch dependency metadata")
    if not any(item.startswith("mpv>=") for item in depends):
        raise ValueError("The system mpv dependency was not detected")
    (workdir / "payload").symlink_to(stage, target_is_directory=True)
    (workdir / "PKGBUILD").write_text(
        f"pkgname=oxplay\npkgver='{package_version}'\npkgrel=1\n"
        "pkgdesc='Experimental native YouTube client'\n"
        f"arch=('{platform.machine()}')\nurl='https://github.com/ViceVerse-cz/oxplay'\n"
        "license=('GPL-3.0-or-later')\noptions=('!strip' '!debug' '!lto')\n"
        + "depends=(" + " ".join(f"'{item}'" for item in sorted(depends)) + ")\n"
        "optdepends=('xdg-desktop-portal: native file dialogs' 'xdg-utils: open links in the browser')\n"
        "package() { cp -a \"$startdir/payload/.\" \"$pkgdir/\"; }\n", encoding="utf-8")
    checked("makepkg", "--nodeps", "--noconfirm", cwd=workdir)
    artifact, = workdir.glob("oxplay-*.pkg.tar.*")
    archive = workdir / "payload.tar"
    with archive.open("wb") as stream:
        subprocess.run(["bsdtar", "-cf", "-", "--format=ustar", "@" + str(artifact)], stdout=stream, check=True)
    extracted = workdir / "extracted"
    extracted.mkdir()
    runnable = executables("usr")
    with tarfile.open(archive) as contents:
        metadata = contents.extractfile(".PKGINFO").read().decode()
        for item in ["pkgname = oxplay", f"pkgver = {package_version}-1", f"arch = {platform.machine()}",
                     *(f"depend = {dependency}" for dependency in depends)]:
            if item not in metadata.splitlines():
                raise ValueError(f"Missing Arch metadata: {item}")
        for member in contents:
            path = Path(member.name)
            if (path.is_absolute() or ".." in path.parts or not (member.isfile() or member.isdir())
                    or member.uid or member.gid):
                raise ValueError(f"Unsafe Arch archive member: {member.name}")
            if member.name in {".PKGINFO", ".BUILDINFO", ".MTREE"}:
                continue
            if member.mode != (0o755 if member.isdir() or member.name in runnable else 0o644):
                raise ValueError(f"Incorrect Arch payload mode: {member.name}")
            contents.extract(member, extracted, filter="data")
    check_payload(stage, extracted)
    print("Arch smoke passed: metadata, dependency versions, payload contents, modes, owners and no scripts.")
    return artifact


def package(format: str, binary: Path, helpers: Path, mpv_prefix: Path | None, version: str, destination: Path) -> Path:
    native_elf(binary)
    if not SEMVER.fullmatch(version):
        raise ValueError("Expected a semantic application version")
    destination.mkdir(parents=True, exist_ok=True)
    if format == "dir":
        target = destination / "linux-root"
        if target.exists() or target.is_symlink():
            raise ValueError(f"Staging destination already exists; move it aside first: {target}")
        stage_payload(target, binary, helpers, mpv_prefix)
        print(f"Linux installation tree: {target}")
        return target
    distro = platform.freedesktop_os_release()
    ids = {distro["ID"], *distro.get("ID_LIKE", "").split()}
    if (format == "deb" and not ids & {"debian", "ubuntu"} or format == "rpm" and distro["ID"] not in {"fedora", "opensuse-tumbleweed"}
            or format == "arch" and "arch" not in ids):
        raise ValueError(f"Build {format} natively on its supported distribution, not {distro['ID']}")
    if format == "arch" and os.getuid() == 0:
        raise ValueError("Run Arch builds as an unprivileged user; makepkg refuses root")
    if format != "deb" and mpv_prefix is not None:
        raise ValueError("RPM and Arch packages use the distribution's libmpv")
    with tempfile.TemporaryDirectory(prefix="oxplay-linux-package-") as directory:
        workdir = Path(directory).resolve()
        stage = workdir / "debian/oxplay"
        stage.parent.mkdir()
        stage_payload(stage, binary, helpers, mpv_prefix)
        checked("desktop-file-validate", stage / "usr/share/applications" / f"{APP_ID}.desktop")
        closure_check(stage)
        if format == "deb":
            artifact = deb_package(workdir, stage, version, mpv_prefix is not None)
        elif format == "rpm":
            artifact = rpm_package(workdir, stage, version, distro["ID"])
        else:
            artifact = arch_package(workdir, stage, version)
        result = destination / artifact.name
        shutil.copyfile(artifact, result)
        print(f"Unsigned {format} package: {result} ({result.stat().st_size} bytes)")
        return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("format", choices=("deb", "rpm", "arch", "dir"))
    parser.add_argument("--binary", type=Path, default=ROOT / "target/release/oxplay")
    parser.add_argument("--helpers", type=Path, required=True, help="Directory from scripts/fetch_pinned.py")
    parser.add_argument("--mpv-prefix", type=Path, help="Private libmpv prefix from scripts/ci/install-mpv-linux.sh")
    parser.add_argument("--version", default=None, help="Defaults to the workspace version")
    parser.add_argument("--output", type=Path, default=ROOT / "dist")
    args = parser.parse_args()
    try:
        package(args.format, args.binary.resolve(strict=True), args.helpers.resolve(strict=True),
                args.mpv_prefix.resolve(strict=True) if args.mpv_prefix else None,
                args.version or workspace_version(), args.output.resolve())
    except (ValueError, OSError, subprocess.CalledProcessError, StopIteration) as error:
        print(f"Linux packaging stopped: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
