#!/usr/bin/env python3
"""Isolated, headed Chrome for Testing local-video diagnostic (never shipped).

`prepare` downloads/verifies the pinned application without launching it.
`run` opens a real window and requires an explicitly coordinated quiet GUI slot.
Only artifacts/local-1080p60.mp4, generated by generate-fixture.sh, is admitted.
No personal profile is opened. Source and binary provenance accompany every run.
"""

import argparse
import fcntl
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import plistlib
import select
import shutil
import signal
import socket
import stat
import subprocess
import sys
import tempfile
import time
import urllib.request
import zipfile

import measure

ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = ROOT / "artifacts/browser-baseline"
VERSION = "154.0.8037.57"
URL = f"https://storage.googleapis.com/chrome-for-testing-public/{VERSION}/mac-arm64/chrome-mac-arm64.zip"
METADATA = f"https://googlechromelabs.github.io/chrome-for-testing/{VERSION}.json"
APP_REL = Path("chrome-mac-arm64/Google Chrome for Testing.app")
EXE_REL = APP_REL / "Contents/MacOS/Google Chrome for Testing"
# Observed from the HTTPS official artifact on 2026-09-29; not a publisher checksum.
ARCHIVE_SHA256 = "0e6b3439469c1b8b95b2e89c72ea29f7af00fb2c28a8878358a0b6002b6d3a64"
PROPERTIES = {"kVideoDecoderName", "kIsPlatformVideoDecoder", "kAudioDecoderName",
              "kIsPlatformAudioDecoder", "kResolution", "kFramerate", "kVideoTracks",
              "kAudioTracks", "pipeline_state", "kRendererName"}


def sha256(path):
    with path.open("rb") as source:
        return hashlib.file_digest(source, "sha256").hexdigest()


def archive_members(archive):
    """Validate the complete archive, including symlink parents, before any write."""
    members = archive.infolist()
    if len(members) > 10000 or sum(m.file_size for m in members) > 2 * 1024**3:
        raise ValueError("archive exceeds extraction bounds")
    paths, links = set(), {}
    for member in members:
        path = PurePosixPath(member.filename)
        if (path.is_absolute() or ".." in path.parts or "\\" in member.filename
                or not path.parts or path.parts[0] != "chrome-mac-arm64"
                or path in paths):
            raise ValueError("unsafe or duplicate archive path")
        paths.add(path)
        mode = member.external_attr >> 16
        if stat.S_ISLNK(mode):
            if member.file_size > 4096:
                raise ValueError("oversized symlink")
            target = PurePosixPath(archive.read(member).decode("utf-8"))
            if target.is_absolute() or ".." in target.parts or not target.parts:
                raise ValueError("unsafe symlink target")
            links[path] = target
        elif stat.S_IFMT(mode) not in (0, stat.S_IFREG, stat.S_IFDIR):
            raise ValueError("unsupported archive special file")
    for path in paths:
        if any(parent in links for parent in path.parents):
            raise ValueError("archive member traverses symlink")
    return members, links


def extract(archive_path, destination):
    with zipfile.ZipFile(archive_path) as archive:
        members, links = archive_members(archive)
        for member in members:
            path = destination / member.filename
            if PurePosixPath(member.filename) in links:
                continue
            if member.is_dir():
                path.mkdir(parents=True, exist_ok=True)
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                with archive.open(member) as source, path.open("xb") as output:
                    shutil.copyfileobj(source, output, 1024 * 1024)
                path.chmod((member.external_attr >> 16) & 0o777 or 0o644)
        for path, target in links.items():
            full = destination / str(path)
            full.parent.mkdir(parents=True, exist_ok=True)
            full.symlink_to(str(target))
        for path in links:
            (destination / str(path)).resolve(strict=True).relative_to(destination.resolve())


def verify_application(base):
    app = base / APP_REL
    strict = subprocess.run(["codesign", "--verify", "--deep", "--strict", str(app)],
                            capture_output=True, text=True, timeout=60)
    signature = subprocess.run(["codesign", "-d", "--verbose=4", str(app)],
                               check=True, capture_output=True, text=True, timeout=10).stderr
    # The actual upstream CfT package is linker-ad-hoc signed and resources are
    # unsealed. Do not pretend it has Developer ID, re-sign it, or alter Gatekeeper.
    if "Signature=adhoc" not in signature or "TeamIdentifier=not set" not in signature:
        raise ValueError("signature differs from inspected pinned artifact")
    subprocess.run(["codesign", "--verify", "--deep", "--strict", "--ignore-resources", str(app)],
                   check=True, capture_output=True, timeout=60)
    archive_path = ARTIFACTS / "chrome-mac-arm64.zip"
    if sha256(archive_path) != ARCHIVE_SHA256:
        raise ValueError("official archive differs from recorded observed digest")
    with zipfile.ZipFile(archive_path) as archive:
        members, links = archive_members(archive)
        expected_files = set()
        for member in members:
            path = base / member.filename
            if member.is_dir():
                continue
            expected_files.add(path.relative_to(base))
            if PurePosixPath(member.filename) in links:
                if not path.is_symlink() or os.readlink(path) != str(links[PurePosixPath(member.filename)]):
                    raise ValueError("framework symlink changed")
            else:
                if path.is_symlink():
                    raise ValueError("unexpected file symlink")
                with archive.open(member) as source:
                    expected = hashlib.file_digest(source, "sha256").hexdigest()
                if sha256(path) != expected:
                    raise ValueError("extracted browser differs from official archive")
        actual_files = {p.relative_to(base) for p in (base / "chrome-mac-arm64").rglob("*")
                        if p.is_symlink() or p.is_file()}
        if actual_files != expected_files:
            raise ValueError("unexpected browser bundle files")
    with (app / "Contents/Info.plist").open("rb") as source:
        info = plistlib.load(source)
    if info["CFBundleShortVersionString"] != VERSION:
        raise ValueError("unexpected browser version")
    architecture = subprocess.check_output(["lipo", "-archs", str(base / EXE_REL)],
                                           text=True, timeout=10).strip()
    if architecture != "arm64":
        raise ValueError("browser must be native ARM64")
    return {"signature": signature, "architecture": architecture,
            "strict_bundle_signature_valid": strict.returncode == 0,
            "strict_bundle_signature_diagnostic": strict.stderr.strip(),
            "code_pages_valid_ignoring_unsealed_resources": True,
            "all_archive_members_verified": True,
            "trust_limit": "Official HTTPS provenance and recorded observed digest; "
                          "ad-hoc code signatures do not authenticate a publisher; resources unsealed.",
            "executable_sha256": sha256(base / EXE_REL)}


def prepare():
    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(METADATA, timeout=30) as response:
        if response.url != METADATA:
            raise ValueError("unexpected release-metadata redirect")
        metadata_bytes = response.read(2 * 1024 * 1024 + 1)
    if len(metadata_bytes) > 2 * 1024 * 1024:
        raise ValueError("oversized official metadata")
    metadata = json.loads(metadata_bytes)
    urls = [item["url"] for item in metadata["downloads"]["chrome"]
            if item["platform"] == "mac-arm64"]
    if metadata["version"] != VERSION or urls != [URL]:
        raise ValueError("pinned URL does not match official release metadata")
    archive = ARTIFACTS / "chrome-mac-arm64.zip"
    if not archive.exists():
        partial = archive.with_suffix(".partial")
        try:
            deadline = time.monotonic() + 300
            total = 0
            with urllib.request.urlopen(URL, timeout=30) as source, partial.open("xb") as out:
                if source.url != URL:
                    raise ValueError("unexpected browser-artifact redirect")
                while chunk := source.read(1024 * 1024):
                    total += len(chunk)
                    if total > 1024**3 or time.monotonic() > deadline:
                        raise ValueError("download bound exceeded")
                    out.write(chunk)
            partial.replace(archive)
        finally:
            partial.unlink(missing_ok=True)
    base = ARTIFACTS / VERSION
    if not base.exists():
        with tempfile.TemporaryDirectory(prefix="extract-", dir=ARTIFACTS) as temporary:
            stage = Path(temporary)
            extract(archive, stage)
            verify_application(stage)
            stage.rename(base)
    verified = verify_application(base)
    result = {"version": VERSION, "url": URL, "metadata_url": METADATA,
              "official_metadata": metadata, "archive_sha256": sha256(archive),
              "verified_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
              **verified}
    (ARTIFACTS / "provenance.json").write_text(json.dumps(result, indent=2))
    print(json.dumps(result, indent=2))


class CDP:
    """One outstanding command, bounded framing and a bounded property inventory."""

    def __init__(self, reader, writer):
        self.reader, self.writer = reader, writer
        self.buffer = bytearray()
        self.serial = 0
        self.players = {}
        self.player_nodes = {}
        self.media_session = None
        self.decoder_epoch = 0
        self.expected_media_url = None
        self.fixture_loads = {}
        self.load_epoch = 0

    def message(self, deadline):
        while b"\0" not in self.buffer:
            remaining = deadline - time.monotonic()
            if remaining <= 0 or not select.select([self.reader], [], [], remaining)[0]:
                raise TimeoutError("CDP response deadline")
            chunk = self.reader.recv(65536)
            if not chunk:
                raise EOFError("browser control pipe closed")
            self.buffer.extend(chunk)
            if len(self.buffer) > 4 * 1024 * 1024:
                raise ValueError("CDP message bound exceeded")
        raw, _, rest = self.buffer.partition(b"\0")
        self.buffer = bytearray(rest)
        return json.loads(raw)

    def event(self, message):
        # Pinned Chromium 154.0.8037.57 domains/Media.pdl: playerCreated
        # carries the optional DOM.BackendNodeId. Missing association fails closed.
        # https://github.com/chromium/chromium/blob/154.0.8037.57/third_party/blink/public/devtools_protocol/domains/Media.pdl
        if message.get("sessionId") != self.media_session:
            return
        method = message.get("method")
        if method == "Media.playerCreated":
            player = message["params"]["player"]
            identity = player["playerId"]
            if identity not in self.player_nodes and len(self.player_nodes) >= 8:
                raise ValueError("unexpected player count")
            self.player_nodes[identity] = player.get("domNodeId")
        elif method == "Media.playerEventsAdded":
            # Actual CfT can omit optional domNodeId. Source-verified kLoad binds
            # its sole player to our sole unchanged element's exact currentSrc.
            # https://github.com/chromium/chromium/blob/154.0.8037.57/media/base/media_log_events.h
            identity = message["params"]["playerId"]
            if identity not in self.fixture_loads and len(self.fixture_loads) >= 8:
                raise ValueError("unexpected media event player count")
            for event in message["params"]["events"]:
                value = json.loads(event["value"])
                if value.get("event") == "kLoad":
                    self.fixture_loads[identity] = (self.expected_media_url is not None
                                                    and value.get("url") == self.expected_media_url)
                    self.load_epoch += 1
                elif value.get("event") == "kWebMediaPlayerDestroyed":
                    self.fixture_loads[identity] = False
                    self.load_epoch += 1
        elif method == "Media.playerPropertiesChanged":
            params = message["params"]
            player_id = params["playerId"]
            if player_id not in self.players and len(self.players) >= 8:
                raise ValueError("unexpected player count")
            player = self.players.setdefault(player_id, {})
            for prop in params["properties"]:
                if prop["name"] in PROPERTIES:
                    value = prop["value"]
                    if value is not None and not isinstance(value, str):
                        raise ValueError("invalid media property type")
                    if prop["name"] in ("kVideoDecoderName", "kIsPlatformVideoDecoder") and player.get(prop["name"]) != value:
                        self.decoder_epoch += 1
                    if value is None:
                        player.pop(prop["name"], None)
                    else:
                        player[prop["name"]] = value[:4096]

    def player_for_node(self, node):
        matches = [identity for identity, backend in self.player_nodes.items() if backend == node]
        if len(matches) == 1 and matches[0] in self.players:
            return matches[0]
        # Never use an unrelated historical hardware player to qualify a new
        # software player. Missing DOM metadata is admitted only for this fully
        # controlled single-element, single-player, exact-fixture source.
        if len(self.player_nodes) == len(self.players) == 1:
            identity, backend = next(iter(self.player_nodes.items()))
            if backend is None and identity in self.players and self.fixture_loads.get(identity):
                return identity
        raise ValueError("current video has no unique CDP player association")

    def call(self, method, params=None, session=None, timeout=10):
        self.serial += 1
        request = {"id": self.serial, "method": method, "params": params or {}}
        if session:
            request["sessionId"] = session
        self.writer.settimeout(timeout)
        self.writer.sendall(json.dumps(request).encode() + b"\0")
        deadline = time.monotonic() + timeout
        for _ in range(4096):
            message = self.message(deadline)
            self.event(message)
            if message.get("id") == self.serial:
                if "error" in message:
                    raise RuntimeError(f"CDP command failed: {method}")
                return message.get("result", {})
        raise ValueError("CDP event flood")

    def evaluate(self, session, expression, gesture=False):
        result = self.call("Runtime.evaluate", {"expression": expression,
                           "returnByValue": True, "awaitPromise": True,
                           "userGesture": gesture}, session)
        if "exceptionDetails" in result:
            raise RuntimeError("fixture JavaScript failed")
        return result["result"].get("value")


SNAPSHOT_JS = """(() => {const v=document.querySelector('video'), r=v.getBoundingClientRect(),
 q=v.getVideoPlaybackQuality(); return {current_time:v.currentTime,duration:v.duration,
 identity_ok:document.querySelectorAll('video').length===1 && v===window.baselineVideo &&
 v.currentSrc===new URL('clip.mp4',location.href).href,
 creation_time:q.creationTime,time_origin:performance.timeOrigin,
 changes:window.baselineChanges,playback_rate:v.playbackRate,
 in_view:r.left>=0 && r.top>=0 && r.right<=innerWidth && r.bottom<=innerHeight,
 width:v.videoWidth,height:v.videoHeight,paused:v.paused,muted:v.muted,volume:v.volume,
 ready_state:v.readyState,error:v.error?.code ?? null,visibility:document.visibilityState,
 focused:document.hasFocus(),css_width:r.width,css_height:r.height,dpr:devicePixelRatio,
 viewport_scale:visualViewport.scale,total_frames:q.totalVideoFrames,
 dropped_frames:q.droppedVideoFrames};})()"""


def qualify(snapshot, players, width, height, player_id):
    if (not snapshot["identity_ok"] or not snapshot["in_view"]
            or snapshot["playback_rate"] != 1 or snapshot["paused"] or snapshot["muted"] or snapshot["volume"] <= 0
            or snapshot["error"] is not None or snapshot["visibility"] != "visible"
            or not snapshot["focused"] or snapshot["ready_state"] < 3
            or snapshot["width"] != 1920 or snapshot["height"] != 1080
            or snapshot["viewport_scale"] != 1
            or abs(snapshot["css_width"] * snapshot["dpr"] - width) > 0.1
            or abs(snapshot["css_height"] * snapshot["dpr"] - height) > 0.1):
        raise ValueError("visible/audible playback or geometry qualification failed")
    player = players.get(player_id, {})
    if (player.get("kVideoDecoderName") != "VideoToolboxVideoDecoder"
            or player.get("kIsPlatformVideoDecoder") != "true"):
        raise ValueError("actual VideoToolbox hardware decoder not established")



def qualify_interval(start, end, elapsed):
    if (end["time_origin"] != start["time_origin"]
            or end["changes"] != start["changes"]
            or end["duration"] != start["duration"]):
        raise ValueError("media/visibility/playback interval continuity failed")
    # W3C media-playback-quality: creationTime dates each quality snapshot;
    # it is not a player generation identifier. Loads are tracked by events.
    # https://w3c.github.io/media-playback-quality/
    counter_elapsed = (end["creation_time"] - start["creation_time"]) / 1000
    if not elapsed * 0.90 <= counter_elapsed <= elapsed * 1.10 + 0.1:
        raise ValueError("media snapshots do not span the recorded interval")
    frames = end["total_frames"] - start["total_frames"]
    dropped = end["dropped_frames"] - start["dropped_frames"]
    advanced = end["current_time"] - start["current_time"]
    if (frames < elapsed * 50 or dropped < 0 or dropped > frames
            or not elapsed * 0.90 <= advanced <= elapsed * 1.10 + 0.1):
        raise ValueError("frame counters or playback time lack continuous forward progress")
    return frames, dropped


def process_inventory(root, selected, table, cdp_processes):
    """Audit the same ps snapshot without storing executable paths or argv."""
    tree = measure.snapshot(root, False, set(), table)
    rows = [{"pid": pid, "parent_pid": row[0],
             "executable": "".join(c for c in Path(row[3]).name if c.isprintable())[:80],
             "attribution": "descendant_tree" if pid in tree else "new_vt_temporal"}
            for pid, row in sorted(selected.items())]
    cdp_ids = {item["id"] for item in cdp_processes}
    selected_ids = set(selected)
    return {"processes": rows, "cdp_not_in_ps_selection": sorted(cdp_ids - selected_ids),
            "ps_selection_not_in_cdp": sorted(selected_ids - cdp_ids),
            "note": "Endpoint snapshots are sequential, not atomic; exited/new processes may differ. "
                    "New VT service membership is temporal, not exclusive ownership proof."}

def launch_browser(binary, profile, log):
    send, child_read = socket.socketpair()
    child_write, receive = socket.socketpair()
    # Keep child descriptors above the destination slots 3/4 to avoid dup collisions.
    read_fd = fcntl.fcntl(child_read.fileno(), fcntl.F_DUPFD_CLOEXEC, 10)
    write_fd = fcntl.fcntl(child_write.fileno(), fcntl.F_DUPFD_CLOEXEC, 10)
    child_read.close()
    child_write.close()
    args = [str(binary), f"--user-data-dir={profile}", "--remote-debugging-pipe",
            "--no-first-run", "--no-default-browser-check", "--disable-background-networking",
            "--disable-component-update", "--disable-sync", "--disable-default-apps",
            "--disable-domain-reliability", "--metrics-recording-only", "--no-pings",
            "--use-mock-keychain", "--host-resolver-rules=MAP * ~NOTFOUND",
            "--window-size=1320,860", "about:blank"]
    try:
        process = subprocess.Popen([sys.executable, str(Path(__file__).resolve()),
                                    "_launch", str(read_fd), str(write_fd), *args],
                                   pass_fds=(read_fd, write_fd), start_new_session=True,
                                   stdout=log, stderr=log)
    except BaseException:
        send.close()
        receive.close()
        raise
    finally:
        os.close(read_fd)
        os.close(write_fd)
    return process, CDP(receive, send), args[1:]


def group_exists(pid):
    try:
        os.killpg(pid, 0)
        return True
    except ProcessLookupError:
        return False


def wait_group_gone(pid, timeout):
    deadline = time.monotonic() + timeout
    while group_exists(pid):
        if time.monotonic() >= deadline:
            return False
        time.sleep(0.05)
    return True


def stop_browser(process, cdp):
    outcome = {"forced_termination": False, "process_group_gone": False,
               "cleanup_errors": []}
    try:
        try:
            cdp.call("Browser.close", timeout=3)
        except (OSError, ValueError, RuntimeError, TimeoutError, EOFError):
            pass
        except BaseException as exc:
            outcome["cleanup_errors"].append(f"{type(exc).__name__}: {exc}")
        try:
            process.wait(timeout=10)
        except subprocess.TimeoutExpired:
            outcome["forced_termination"] = True
        # Parent exit is not child-group exit. Check again after SIGKILL, too.
        for termination in (signal.SIGTERM, signal.SIGKILL):
            if not group_exists(process.pid):
                break
            outcome["forced_termination"] = True
            try:
                os.killpg(process.pid, termination)
            except ProcessLookupError:
                pass
            try:
                process.wait(timeout=3)
            except subprocess.TimeoutExpired:
                pass
            if wait_group_gone(process.pid, 3):
                break
        process.wait(timeout=3)  # reap our direct child even after group shutdown
        outcome["process_group_gone"] = not group_exists(process.pid)
    except BaseException as exc:
        outcome["cleanup_errors"].append(f"{type(exc).__name__}: {exc}")
    finally:
        for stream in (cdp.reader, cdp.writer):
            try:
                stream.close()
            except BaseException as exc:
                outcome["cleanup_errors"].append(f"{type(exc).__name__}: {exc}")
        outcome["exit_code"] = process.returncode
    return outcome


def finalize(run_dir, result, process, cdp):
    """Always preserve measurements; uncertain child ownership retains its profile."""
    outcome = {"process_group_gone": process is None, "forced_termination": False,
               "cleanup_errors": [], "exit_code": None}
    if process is not None:
        try:
            outcome.update(stop_browser(process, cdp))
        except BaseException as exc:
            outcome["cleanup_errors"].append(f"{type(exc).__name__}: {exc}")
    result.update(outcome)
    if (not outcome["process_group_gone"] or outcome["forced_termination"]
            or outcome["cleanup_errors"] or (process is not None and outcome["exit_code"] != 0)):
        result["status"] = "incomplete"
    result["profile_retained_for_live_or_unknown_group"] = not outcome["process_group_gone"]
    # Persist before optional filesystem cleanup so a removal error loses no data.
    evidence = run_dir / "result.json"
    evidence.write_text(json.dumps(result, indent=2))
    if outcome["process_group_gone"]:
        try:
            profile = run_dir / "profile"
            if profile.exists():
                shutil.rmtree(profile)
            (run_dir / "clip.mp4").unlink(missing_ok=True)
        except BaseException as exc:
            result["cleanup_errors"].append(f"{type(exc).__name__}: {exc}")
            result["status"] = "incomplete"
    evidence.write_text(json.dumps(result, indent=2))


def run(args):
    if not (1 <= args.seconds <= 60 and 0 <= args.warmup <= 15):
        raise ValueError("run duration must fit the bounded 90-second fixture")
    if not (1 <= args.width <= 2560 and 1 <= args.height <= 1600):
        raise ValueError("invalid fixture geometry")
    base = ARTIFACTS / VERSION
    verified = verify_application(base)
    provenance = json.loads((ARTIFACTS / "provenance.json").read_text())
    if verified["executable_sha256"] != provenance["executable_sha256"]:
        raise ValueError("prepared browser changed")
    clip = ROOT / "artifacts/local-1080p60.mp4"
    if not clip.is_file() or clip.is_symlink():
        raise ValueError("generate the local fixture first; symlinks are not admitted")
    run_dir = Path(tempfile.mkdtemp(prefix="run-", dir=ARTIFACTS))
    run_dir.chmod(0o700)
    # A hard link admits only the owned generated fixture, not arbitrary personal media.
    os.link(clip, run_dir / "clip.mp4")
    (run_dir / "index.html").write_text("""<!doctype html><meta charset=utf-8>
<meta http-equiv=Content-Security-Policy content="default-src 'none'; media-src 'self'; style-src 'unsafe-inline'">
<title>Serein local browser baseline</title><style>html,body{margin:0;background:#161616}
video{display:block;object-fit:contain}</style><video preload=none playsinline></video>""")
    result = {"browser": provenance, "harness_sha256": sha256(Path(__file__)),
              "clip_sha256": sha256(clip), "warmup_seconds": args.warmup,
              "physical_video_width": args.width, "physical_video_height": args.height,
              "include_new_vt_services": args.include_new_vt_services,
              "status": "incomplete", "samples": []}
    baseline = set(measure.process_table())
    process, cdp = None, None
    error = None
    with (run_dir / "browser.log").open("w") as log:
        try:
            process, cdp, flags = launch_browser(base / EXE_REL, run_dir / "profile", log)
            result["flags"] = [f if not f.startswith("--user-data-dir=") else
                               "--user-data-dir=<isolated-run-profile>" for f in flags]
            result["runtime_version"] = cdp.call("Browser.getVersion")
            target_deadline = time.monotonic() + 10
            while True:
                targets = cdp.call("Target.getTargets")["targetInfos"]
                target = next((t for t in targets if t["type"] == "page"), None)
                if target is not None:
                    break
                if time.monotonic() >= target_deadline:
                    raise TimeoutError("native browser page startup deadline")
                time.sleep(0.05)
            session = cdp.call("Target.attachToTarget", {"targetId": target["targetId"],
                                                        "flatten": True})["sessionId"]
            cdp.call("Page.enable", session=session)
            cdp.call("DOM.enable", session=session)
            cdp.media_session = session
            cdp.expected_media_url = (run_dir / "clip.mp4").as_uri()
            cdp.call("Media.enable", session=session)
            cdp.call("Network.enable", session=session)
            cdp.call("Network.setBlockedURLs", {"urls": ["http://*", "https://*"]}, session)
            cdp.call("Page.navigate", {"url": (run_dir / "index.html").as_uri()}, session)
            deadline = time.monotonic() + 10
            while not cdp.evaluate(session, "document.querySelector('video') !== null"):
                if time.monotonic() > deadline:
                    raise TimeoutError("fixture navigation deadline")
                time.sleep(0.05)
            document = cdp.call("DOM.getDocument", session=session)["root"]["nodeId"]
            node = cdp.call("DOM.querySelector", {"nodeId": document, "selector": "video"}, session)["nodeId"]
            backend_node = cdp.call("DOM.describeNode", {"nodeId": node}, session)["node"]["backendNodeId"]
            cdp.evaluate(session, """(() => {window.baselineVideo=document.querySelector('video');
window.baselineChanges=0; const changed=()=>{window.baselineChanges++};
for(const event of ['pause','seeking','emptied','loadedmetadata','ratechange','volumechange'])
 baselineVideo.addEventListener(event,changed);
for(const event of ['blur','resize']) window.addEventListener(event,changed);
document.addEventListener('visibilitychange',changed);})()""")
            cdp.call("Page.bringToFront", session=session)
            cdp.evaluate(session, f"""(() => {{const v=document.querySelector('video');
v.style.width=({args.width}/devicePixelRatio)+'px';
v.style.height=({args.height}/devicePixelRatio)+'px';v.src='clip.mp4';return v.play();}})()""", True)
            time.sleep(args.warmup)
            start_media = cdp.evaluate(session, SNAPSHOT_JS)
            result["media_start"] = start_media
            result["decoder_start"] = list(cdp.players.values())
            result["player_nodes"] = dict(cdp.player_nodes)
            result["video_backend_node"] = backend_node
            selected_player = cdp.player_for_node(backend_node)
            decoder_epoch = cdp.decoder_epoch
            load_epoch = cdp.load_epoch
            result["decoder_association"] = "backend_dom_node" if cdp.player_nodes[selected_player] is not None else "sole_player_exact_fixture_load"
            result["selected_player"] = selected_player
            qualify(start_media, cdp.players, args.width, args.height, selected_player)
            media_start_clock = time.monotonic()
            result["cdp_processes_start"] = cdp.call("SystemInfo.getProcessInfo")["processInfo"]
            result["native_window"] = cdp.call("Browser.getWindowForTarget",
                                               {"targetId": target["targetId"]})
            previous_table = measure.process_table()
            previous = measure.snapshot(process.pid, args.include_new_vt_services,
                                        baseline, previous_table)
            result["process_inventory_start"] = process_inventory(
                process.pid, previous, previous_table, result["cdp_processes_start"])
            result["measurement_start_utc"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
            last = start = time.monotonic()
            for index in range(args.seconds):
                time.sleep(max(0, start + index + 1 - time.monotonic()))
                now = time.monotonic()
                table = measure.process_table()
                current = measure.snapshot(process.pid, args.include_new_vt_services, baseline, table)
                if process.poll() is not None:
                    raise RuntimeError("browser exited during measurement")
                result["samples"].append({"rss_mib": sum(v[1] for v in current.values()) / 1024,
                    "cpu_one_core_percent": 100 * measure.cpu_delta(current, previous) / (now-last),
                    "processes": len(current), "elapsed_after_warmup_seconds": now-start,
                    **measure.host_other_cpu(table, previous_table, set(current), now-last)})
                previous, previous_table, last = current, table, now
            end_media = cdp.evaluate(session, SNAPSHOT_JS)
            result["media_end"] = end_media
            result["decoder_end"] = list(cdp.players.values())
            media_elapsed = time.monotonic() - media_start_clock
            if (cdp.player_for_node(backend_node) != selected_player
                    or cdp.decoder_epoch != decoder_epoch or cdp.load_epoch != load_epoch):
                raise ValueError("selected native decoder changed during measurement")
            qualify(end_media, cdp.players, args.width, args.height, selected_player)
            result["cdp_processes_end"] = cdp.call("SystemInfo.getProcessInfo")["processInfo"]
            result["process_inventory_end"] = process_inventory(
                process.pid, previous, previous_table, result["cdp_processes_end"])
            result["media_counter_interval_seconds"] = media_elapsed
            result["frame_delta"], result["dropped_frame_delta"] = qualify_interval(start_media, end_media, media_elapsed)
            for name in ("rss_mib", "cpu_one_core_percent", "host_other_cpu_one_core_percent"):
                result[name] = measure.statistics([row[name] for row in result["samples"]])
            result["status"] = "completed_not_automatically_qualified"
        except BaseException as exc:
            error = exc
            result["failure"] = f"{type(exc).__name__}: {exc}"
        finally:
            result["notes"] = ("RSS can double-count shared pages; GPU memory is not added. "
                "Short-lived/reparented helpers can escape ps attribution; compare CDP PID inventory. "
                "New VT services are temporally attributed, not proven exclusively owned. "
                "Host-other CPU includes harness/system work and is never charged to the browser. "
                "CSS physical geometry does not establish compositor allocation size or scanout. "
                "DOM visibility/focus and transition events do not prove native unoccluded scanout, "
                "display wake state or audible device output. Video counters measure submitted/dropped "
                "frames, not compositor presentation. No continuous GPU or audio-route probe is made. "
                "Decoder evidence, audible output, display state, dropped-frame gate and "
                "foreign-work audit require review before comparison. Background flags and page URL "
                "blocking are not comprehensive whole-browser egress verification.")
            finalize(run_dir, result, process, cdp)
    print(run_dir / "result.json")
    if error:
        raise error
    if result["status"] == "incomplete":
        raise RuntimeError("browser did not exit cleanly")


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "_launch":
        # This process immediately becomes Chrome; no separate persistent driver process.
        read_fd, write_fd = map(int, sys.argv[2:4])
        os.dup2(read_fd, 3)
        os.dup2(write_fd, 4)
        os.close(read_fd)
        os.close(write_fd)
        os.execv(sys.argv[4], sys.argv[4:])
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("prepare")
    run_parser = sub.add_parser("run")
    run_parser.add_argument("--warmup", type=int, default=10)
    run_parser.add_argument("--seconds", type=int, default=60)
    run_parser.add_argument("--width", type=int, default=1384)
    run_parser.add_argument("--height", type=int, default=778)
    run_parser.add_argument("--include-new-vt-services", action="store_true")
    args = parser.parse_args()
    if args.command == "prepare":
        prepare()
    else:
        def terminated(signum, _frame):
            raise InterruptedError(f"harness received signal {signum}")
        previous = signal.signal(signal.SIGTERM, terminated)
        try:
            run(args)
        finally:
            signal.signal(signal.SIGTERM, previous)


if __name__ == "__main__":
    main()
