[package]
name = "serein-network"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serein-core = { path = "../core" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
tokio = { version = "1", features = ["rt", "time", "net", "sync", "macros"] }
url = "2.5"

[target.'cfg(not(target_os = "macos"))'.dependencies]
hickory-resolver = { version = "=0.26.3", default-features = false, features = ["system-config", "tokio"] }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"

[dev-dependencies]
serein-youtube = { path = "../youtube" }
